<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=2.0">
    <title>Happy 11 Months, My Princess!</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin-top: 100px;
            background: rgb(138, 212, 247);
        }
        h1 {
            color: #698cff;
            height: 200;
        }
        .heart {
            width: 500px;
            height: auto;
            margin: 20px;
        }
    </style>
</head>
<body>
    <h1>Happy 11 Months, My Princess!</h1>
    <img src="https://png.pngtree.com/png-clipart/20220918/ourmid/pngtree-floating-realistic-clouds-png-image_6195497.png" alt="Cloud" width="500">
    <img src="https://png.pngtree.com/png-vector/20220411/ourmid/pngtree-glossy-heart-best-vector-ai-and-png-png-image_4538478.png" alt="Heart" class="heart" height="600">
    <img src="https://img.freepik.com/free-vector/transparent-vector-white-cloud-sky-realistic-set-fog-smoke-png-texture-isolated-design-abstract-cloudy-air-effect-with-day-light-icon-collection-3d-beautiful-nature-atmosphere-vapor-smoky-steam_107791-21341.jpg?w=1800&t=st=1715049619~exp=1715050219~hmac=2c0f0cd35937aa5aa4d4be62e3cfbc221d2a15c4b20ab707d6603345ad4ede30" alt="Cloud" width="500">
    <p>Me haces el niño mas feliz del mundo y esto me costo 5 osea cuando no estabas pelo nunca podia pero alfinnnn pude y with you funcionaba teeeee ammoooooo!</p>
    <p>muchisisiisisiisisiisiisisimo,</p>
    <p>Dani tu princesito</p>
    <p>En teoria debio haber quedado mach bonito</p>
    <p>no sabes lo imposible que fue peeeeeloooo chiiiiii pude</p>
    <p>TE AMO CON MI VIDA ENTERA y chi aunque quisiela obviamente celebrarlo de una manera en la que no sea a veces erte lejos de ti pelo de verdad gracias</p>
    <p>por todo lo que haces por mi y tambien no che encontrar alguna forma o demostrarte que este tiempo que nos damos si va a servir y que lo hacemos por</p>
    <p>VALENTINO y porque vamos a ser mejores y nos vamos a amar mucho tambien a me complometo a no sacarte mach canas verdes y gracias por aguantarme y</p>
    <p>tener que entenderme siempre de verdad que is lo aprecio y creo que sabes que tu noviecito no es tan fisico lo regalos tambien epelo y te baya a gustar </p>
    <p>los regalos que tengo pala ti TE CIELO</p>
    <p>PISTA ES DEL COLOR DEL FONDO</p>
    <P> THE GIFT =) </P>
</body>
</html>
